# Netlify Configuration - SalaFácil
[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions
[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

# SPA Redirect - DEVE SER O ÚLTIMO
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Force correct MIME types
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"  
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
