# Netlify Configuration - Ultra Simples  
[build]
  base = "frontend"
  command = "rm -rf dist node_modules && npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Functions usando bundler mais estável
[functions]
  directory = "../netlify/functions"
  node_bundler = "zisi"

# Redirects com prioridade correta  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - excluir paths específicos
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
