# Netlify Configuration - SalaFácil com Chat e Notificações
[build]
  base = "frontend"
  command = "npm install --prefix .. && rm -f package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Variáveis para o sistema de chat
  REACT_APP_API_URL = "https://your-backend-url.herokuapp.com"
  REACT_APP_VAPID_PUBLIC_KEY = "your-vapid-public-key-here"

# Netlify Functions (Backend)
[functions]
  directory = "../netlify/functions"

# Variáveis de ambiente para desenvolvimento local
[context.development.environment]
  DATABASE_URL = "sua-connection-string-neon-aqui"
  JWT_SECRET = "sua-chave-jwt-super-secreta-aqui"
  VAPID_PRIVATE_KEY = "sua-vapid-private-key"
  VAPID_PUBLIC_KEY = "sua-vapid-public-key"
  EMAIL_HOST_USER = "seu-email@gmail.com"
  EMAIL_HOST_PASSWORD = "sua-senha-de-app"

# Variáveis de ambiente para produção (configurar no Netlify Dashboard)
# [context.production.environment]
  # NODE_ENV removido para permitir devDependencies no build

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and PWA support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Service Worker headers for PWA
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Manifest file for PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CORS for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
