# Netlify Configuration - SalaFácil
[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions
[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg", "jsonwebtoken", "bcryptjs"]

# Redirects - API primeiro, depois SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA - apenas para páginas, não assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["*"]}

# Headers para tipos MIME corretos
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"  
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
