# Netlify Configuration - Ultra Simples  
[build]
  command = "cd frontend && rm -rf dist node_modules && npm ci && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SKIP_CACHE = "true"

# Functions usando bundler mais estável
[functions]
  directory = "netlify/functions"
  node_bundler = "zisi"

# Apenas o essencial
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
