# Generated by Django 4.2.23 on 2025-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da sala'),
        ),
        migrations.AddField(
            model_name='sala',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: 1º Andar, Ala A', max_length=200),
        ),
    ]
