# Generated by Django 4.2.23 on 2025-07-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0002_sala_descricao_sala_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='agendamento.department', verbose_name='Departamento Pai')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='user', max_length=20, verbose_name='Função')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('blocked', 'Bloqueado'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='Status')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado em')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('google_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('picture_url', models.URLField(blank=True, verbose_name='Foto do perfil')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='agendamento.department', verbose_name='Departamento')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='agendamento.userprofile', verbose_name='Gerente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('type', models.CharField(choices=[('admin_message', 'Mensagem Administrativa'), ('system_alert', 'Alerta do Sistema'), ('room_reminder', 'Lembrete de Sala'), ('maintenance', 'Manutenção')], default='admin_message', max_length=50, verbose_name='Tipo')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Notificação Push',
                'verbose_name_plural': 'Notificações Push',
                'db_table': 'push_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Criar Usuário'), ('update_user', 'Atualizar Usuário'), ('delete_user', 'Deletar Usuário'), ('block_user', 'Bloquear Usuário'), ('unblock_user', 'Desbloquear Usuário'), ('create_department', 'Criar Departamento'), ('update_department', 'Atualizar Departamento'), ('delete_department', 'Deletar Departamento'), ('send_notification', 'Enviar Notificação'), ('login', 'Login'), ('logout', 'Logout')], max_length=50, verbose_name='Ação')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Alvo')),
            ],
            options={
                'verbose_name': 'Log Administrativo',
                'verbose_name_plural': 'Logs Administrativos',
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
